plugin: amazon.aws.aws_ec2                         
regions:
  - us-east-1                                  

filters:
  instance-state-name: running              

hostnames:
  - private-ip-address                        

compose:
  ansible_host: private_ip_address             

keyed_groups:
  - key: tags.Name                            
    prefix: ""                                 