plugin: amazon.aws.aws_ec2                         
regions:
  - us-east-1                                  

filters:
  instance-state-name: running 
  "tag:Name": my-portfolio-dev-ec2             

hostnames:
  - private_ip_address                        

compose:
  ansible_host: private_ip_address       

groups:
  my_portfolio_dev_ec2: "'my-portfolio-dev-ec2' in tags.Name"      

keyed_groups:
  - key: tags.Name                            
    prefix: ""                                 